namespace wslc_desktop.Services;

public interface IStringLocalizer
{
    string CurrentLanguage { get; }

    string Get(string key);

    string Get(string key, string language);

    string Format(string key, params object[] args);
}

public sealed class AppStringLocalizer : IStringLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["SettingsPageTitle"] = "Settings",
        ["SettingsRestartRequired"] = "Settings saved. Restart the app or wslcd-desktop to apply runtime and language changes.",
        ["SettingsStored"] = "Settings are stored in the app data directory.",
        ["SettingsSaved"] = "Settings saved.",
        ["SettingsSavedDaemonRestartRecommended"] = "Settings saved. Restart wslcd-desktop to apply daemon runtime changes.",
        ["DiagnosticsExported"] = "Diagnostics exported to {0}.",
        ["SettingsSavedStartupUnavailable"] = "Settings saved. Startup registration is unavailable: {0}",
        ["ProviderPreviewNotTested"] = "Provider connection has not been tested.",
        ["ProviderPreviewAvailable"] = "{0} is available. Capabilities: {1}.",
        ["ProviderPreviewUnavailable"] = "{0} is unavailable. {1}",
        ["StartupTaskStatusUnknown"] = "Startup task status has not been checked.",
        ["DaemonStarted"] = "wslcd-desktop started.",
        ["DaemonRestarted"] = "wslcd-desktop restarted.",
        ["DaemonStopped"] = "wslcd-desktop stopped. Resource pages may start it again when needed.",
        ["DaemonStopWarning"] = " Warning: {0}",
        ["DaemonStartDialogTitle"] = "Start wslcd-desktop?",
        ["DaemonStartDialogContent"] = "These settings apply when wslcd-desktop starts. Start the daemon now?",
        ["DaemonRestartDialogTitle"] = "Restart wslcd-desktop?",
        ["DaemonRestartDialogContent"] = "This stops existing daemon processes and starts a fresh wslcd-desktop instance. Active Docker CLI calls may be interrupted.",
        ["DaemonStopDialogTitle"] = "Stop wslcd-desktop?",
        ["DaemonStopDialogContent"] = "This stops existing daemon processes and leaves the daemon offline until you start it again or another app workflow starts it.",
        ["DockerConfigOpened"] = "Docker configuration folder opened.",
        ["WslcRequiredDialogTitle"] = "WSLC is required",
        ["WslcRequiredMissingWslMessage"] = "WSLC currently requires the WSL pre-release build. Install or update WSL with the commands below before using WSLC Desktop.",
        ["WslcRequiredUpdateRequiredMessage"] = "WSL is installed, but wslc.exe is missing. Update WSL to the pre-release build, then install WSLC if required.",
        ["WslcRequiredUpdateRequiredWithVersion"] = "WSL is installed, but wslc.exe is missing. Update WSL to the pre-release build, then install WSLC if required. Detected: {0}",
        ["WslcRequiredTimedOutMessage"] = "WSLC prerequisite check timed out. Run the commands below, then recheck.",
        ["WslcRequiredCommandHeader"] = "Run these commands in Windows Terminal, one line at a time:",
        ["DockerCliOptionalDialogTitle"] = "Docker CLI is optional",
        ["DockerCliOptionalDialogContent"] = "Docker CLI was not found on PATH. You can install the CLI helper now or continue using the GUI only.",
        ["OpenSettings"] = "Open settings",
        ["Later"] = "Later",
        ["Recheck"] = "Recheck",
        ["CopyCommand"] = "Copy command",
        ["Exit"] = "Exit",
        ["CliToolsStatusUnknown"] = "CLI tool status has not been checked.",
        ["CliToolsPathAdded"] = "Added {0} to the user PATH. Open a new terminal for the change to take effect.",
        ["CliToolsSystemPathAdded"] = "Added {0} to the system PATH. Open a new terminal for the change to take effect.",
        ["CliToolsOperationFailed"] = "CLI tool operation failed: {0}",
        ["CliToolsWslcReady"] = "wslc.exe is available.",
        ["CliToolsWslcMissing"] = "wslc.exe is unavailable. Run: {0}",
        ["CliToolsDockerReady"] = "docker.exe is available: {0}",
        ["CliToolsDockerMissing"] = "docker.exe is not installed.",
        ["CliToolsComposeReady"] = "Docker Compose is available: {0}",
        ["CliToolsComposeMissing"] = "Docker Compose is not installed.",
        ["CliToolsDialogTitle"] = "CLI tool setup",
        ["CliToolsDialogDescription"] = "Install or repair the Docker CLI and Docker Compose helpers used by external docker commands.",
        ["CliToolsDialogStatusTitle"] = "CLI tools status",
        ["CliToolsDialogInstallDirectory"] = "Install directory",
        ["CliToolsDialogRefresh"] = "Refresh",
        ["CliToolsDialogRefreshed"] = "CLI tool status refreshed.",
        ["CliToolsDialogInstallDocker"] = "Install Docker CLI",
        ["CliToolsDialogInstallDockerZip"] = "Install Docker ZIP",
        ["CliToolsDialogInstallCompose"] = "Install Compose",
        ["CliToolsDialogSelectComposeExe"] = "Select Compose EXE",
        ["CliToolsDialogAddUserPath"] = "Add user PATH",
        ["CliToolsDialogAddSystemPath"] = "Add system PATH",
        ["CliToolsDialogNoFileSelected"] = "No file selected.",
        ["DockerContextDefaultConfirmTitle"] = "Use WSLC Desktop Docker context?",
        ["DockerContextDefaultConfirmContent"] = "This creates the docker context 'wslc-desktop' if it is missing, then sets it as the default Docker CLI context for the current user.",
        ["DockerContextDefaultConfirmPrimary"] = "Use as default",
        ["DockerContextDefaultCreated"] = "Docker context '{0}' is now the default and points to {1}.",
        ["ShellStatusChecking"] = "Checking",
        ["ShellStatusDaemonOk"] = "Daemon OK",
        ["ShellStatusDaemonOffline"] = "Daemon offline",
        ["ShellStatusDaemonWarning"] = "Daemon issue",
        ["ShellStatusRuntimeOk"] = "Runtime OK",
        ["ShellStatusRuntimeIssue"] = "Runtime issue",
        ["ShellStatusBackendUnknown"] = "Backend unknown",
        ["Start"] = "Start",
        ["Restart"] = "Restart",
        ["Stop"] = "Stop",
        ["EngineReady"] = "Ready",
        ["EngineMissingComponents"] = "Missing components",
        ["EngineUnsupported"] = "Unsupported",
        ["EngineError"] = "Error",
        ["EngineUnknown"] = "Unknown",
        ["ContainerCount"] = "{0} container{1}",
        ["ImageCount"] = "{0} cached",
        ["ImagesAvailable"] = "{0} image{1} available.",
        ["ImagesSummary"] = "{0} images",
        ["ImagePullStart"] = "Starting image pull...",
        ["ImagePulling"] = "Pulling {0}: {1}/{2} bytes",
        ["ImagePullingStatus"] = "Pulling {0}: {1}",
        ["ImagePullComplete"] = "Image pull completed.",
        ["ImagePullTaskQueued"] = "Queued",
        ["ImagePullTaskPulling"] = "Pulling",
        ["ImagePullTaskCompleted"] = "Completed",
        ["ImagePullTaskFailed"] = "Failed",
        ["ImagePullTasksSummary"] = "{0} active · {1} total",
        ["ImageDeleted"] = "Image deleted.",
        ["PullImageTitle"] = "Pull Image",
        ["PullImageReference"] = "Image reference",
        ["Pull"] = "Pull",
        ["InUse"] = "In use",
        ["Unused"] = "Unused",
        ["ComposeNoProjects"] = "No compose projects have been created yet.",
        ["ComposeProjectsLoaded"] = "{0} compose project{1} tracked.",
        ["ComposePlansGenerated"] = "{0} service plan{1} generated from {2}.",
        ["ComposeContainersCreated"] = "{0} service container{1} created and started.",
        ["ComposeSummary"] = "{0} projects · {1} planned services",
        ["ComposeProjectStatus"] = "{0} running / {1} services",
        ["VolumesTracked"] = "{0} volume{1} from the default wslc control plane.",
        ["VolumesSummary"] = "{0} volumes",
        ["NamedVolumeCreated"] = "Named volume {0} created.",
        ["NamedVolumeDeleted"] = "Named volume {0} deleted.",
        ["CreateVolumeTitle"] = "New Volume",
        ["VolumeNameInput"] = "Name",
        ["VolumeSizeInput"] = "Size MB",
        ["VolumeDetailName"] = "Name",
        ["VolumeDetailKind"] = "Driver",
        ["VolumeDetailSize"] = "Size",
        ["VolumeDetailUsedBy"] = "Used by",
        ["VolumeDetailCreated"] = "Created",
        ["NamedVolumeKind"] = "local",
        ["BindVolumeKind"] = "bind",
        ["NetworksPublishedPorts"] = "{0} published endpoint{1} from wslc containers.",
        ["NetworkEndpointsSummary"] = "{0} published endpoints",
        ["EndpointDetailContainer"] = "Container",
        ["EndpointDetailHostPort"] = "Host port",
        ["EndpointDetailContainerPort"] = "Container port",
        ["EndpointDetailProtocol"] = "Protocol",
        ["EndpointDetailUrl"] = "URL",
        ["ContainersLoaded"] = "{0} container{1}.",
        ["ContainersSummary"] = "{0} running · {1} stopped",
        ["ContainersNoSelection"] = "No container selected",
        ["ContainersSelectContainerDetail"] = "Select a container to inspect details.",
        ["InspectUnavailable"] = "Inspect data is not available.",
        ["LogsUnavailable"] = "Logs are not available.",
        ["PreviewTruncated"] = "... {0} more line(s). Use expand to view all.",
        ["ContainerCreated"] = "Container {0} created.",
        ["ContainerStarted"] = "Start requested for {0}.",
        ["ContainerStopped"] = "Stop requested for {0}.",
        ["ContainerRestarted"] = "Restart requested for {0}.",
        ["ContainerDeleted"] = "Container deleted.",
        ["TerminalNoContainer"] = "Select a running container before connecting a shell.",
        ["TerminalReadyMessage"] = "Terminal is ready. Connect a running container to open a shell.\n",
        ["TerminalConnectingMessage"] = "Connecting to {0}...\n",
        ["TerminalConnectedMessage"] = "[connected: {0}]\n",
        ["TerminalConnectFailed"] = "[terminal failed: {0}]\n",
        ["TerminalStateDisconnected"] = "Disconnected",
        ["TerminalStateConnecting"] = "Connecting",
        ["TerminalStateConnected"] = "Connected",
        ["TerminalStateExited"] = "Exited",
        ["TerminalStateFailed"] = "Failed",
        ["ContainersLogsDialogTitle"] = "Logs",
        ["ContainersTerminalDialogTitle"] = "Terminal",
        ["ContainersInspectDialogTitle"] = "Inspect",
        ["Delete"] = "Delete",
        ["Cancel"] = "Cancel",
        ["Close"] = "Close",
        ["Create"] = "Create",
        ["CreateContainerTitle"] = "New Container",
        ["CreateContainerImage"] = "Image",
        ["CreateContainerName"] = "Name (optional)",
        ["CreateContainerCommand"] = "Command",
        ["CreateContainerPorts"] = "Ports (host:container, comma-separated)",
        ["CreateContainerMounts"] = "Mounts (source=>target, comma-separated)",
        ["CreateContainerEnvironment"] = "Environment (KEY=value, comma-separated)",
        ["DeleteImageTitle"] = "Delete image?",
        ["DeleteContainerTitle"] = "Delete container?",
        ["DeleteVolumeTitle"] = "Delete named volume",
        ["DeleteVolumeContent"] = "Delete named volume '{0}' from the default wslc control plane?"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["SettingsPageTitle"] = "设置",
        ["SettingsRestartRequired"] = "设置已保存。请重启应用或 wslcd-desktop 以应用运行时和语言更改。",
        ["SettingsStored"] = "设置保存在应用数据目录中。",
        ["SettingsSaved"] = "设置已保存。",
        ["SettingsSavedDaemonRestartRecommended"] = "设置已保存。请重启 wslcd-desktop 以应用 daemon 运行时变更。",
        ["DiagnosticsExported"] = "诊断信息已导出到 {0}。",
        ["SettingsSavedStartupUnavailable"] = "设置已保存。开机启动注册不可用：{0}",
        ["ProviderPreviewNotTested"] = "尚未测试 Provider 连接。",
        ["ProviderPreviewAvailable"] = "{0} 可用。能力：{1}。",
        ["ProviderPreviewUnavailable"] = "{0} 不可用。{1}",
        ["StartupTaskStatusUnknown"] = "尚未检查开机启动状态。",
        ["DaemonStarted"] = "wslcd-desktop 已启动。",
        ["DaemonRestarted"] = "wslcd-desktop 已重启。",
        ["DaemonStopped"] = "wslcd-desktop 已关闭。资源页面需要时可能会重新启动它。",
        ["DaemonStopWarning"] = " 警告：{0}",
        ["DaemonStartDialogTitle"] = "启动 wslcd-desktop？",
        ["DaemonStartDialogContent"] = "这些设置会在 wslcd-desktop 启动时生效。是否现在启动 daemon？",
        ["DaemonRestartDialogTitle"] = "重启 wslcd-desktop？",
        ["DaemonRestartDialogContent"] = "这会停止现有 daemon 进程并启动新的 wslcd-desktop 实例。正在运行的 Docker CLI 调用可能会中断。",
        ["DaemonStopDialogTitle"] = "关闭 wslcd-desktop？",
        ["DaemonStopDialogContent"] = "这会停止现有 daemon 进程，并保持离线，直到你再次启动或其他应用工作流重新拉起它。",
        ["DockerConfigOpened"] = "已打开 Docker 配置目录。",
        ["WslcRequiredDialogTitle"] = "需要 WSLC",
        ["WslcRequiredMissingWslMessage"] = "WSLC 目前需要 WSL 预览版。请先使用下面的命令安装或更新 WSL，然后再使用 WSLC Desktop。",
        ["WslcRequiredUpdateRequiredMessage"] = "已检测到 WSL，但缺少 wslc.exe。请先将 WSL 更新到预览版，如仍缺失再安装 WSLC。",
        ["WslcRequiredUpdateRequiredWithVersion"] = "已检测到 WSL，但缺少 wslc.exe。请先将 WSL 更新到预览版，如仍缺失再安装 WSLC。检测到：{0}",
        ["WslcRequiredTimedOutMessage"] = "WSLC 前置检查超时。请运行下面的命令，然后重新检测。",
        ["WslcRequiredCommandHeader"] = "请在 Windows Terminal 中逐行运行这些命令：",
        ["DockerCliOptionalDialogTitle"] = "Docker CLI 可选安装",
        ["DockerCliOptionalDialogContent"] = "未在 PATH 中找到 Docker CLI。你可以现在安装 CLI 辅助工具，也可以继续只使用图形界面。",
        ["OpenSettings"] = "打开设置",
        ["Later"] = "稍后",
        ["Recheck"] = "重新检测",
        ["CopyCommand"] = "复制命令",
        ["Exit"] = "退出",
        ["CliToolsStatusUnknown"] = "尚未检查 CLI 工具状态。",
        ["CliToolsPathAdded"] = "已将 {0} 添加到用户 PATH。请打开新的终端让变更生效。",
        ["CliToolsSystemPathAdded"] = "已将 {0} 添加到系统 PATH。请打开新的终端让变更生效。",
        ["CliToolsOperationFailed"] = "CLI 工具操作失败：{0}",
        ["CliToolsWslcReady"] = "wslc.exe 可用。",
        ["CliToolsWslcMissing"] = "wslc.exe 不可用。请运行：{0}",
        ["CliToolsDockerReady"] = "docker.exe 可用：{0}",
        ["CliToolsDockerMissing"] = "docker.exe 未安装。",
        ["CliToolsComposeReady"] = "Docker Compose 可用：{0}",
        ["CliToolsComposeMissing"] = "Docker Compose 未安装。",
        ["CliToolsDialogTitle"] = "CLI 工具安装",
        ["CliToolsDialogDescription"] = "安装或修复外部 docker 命令使用的 Docker CLI 和 Docker Compose 辅助工具。",
        ["CliToolsDialogStatusTitle"] = "CLI 工具状态",
        ["CliToolsDialogInstallDirectory"] = "安装目录",
        ["CliToolsDialogRefresh"] = "刷新",
        ["CliToolsDialogRefreshed"] = "CLI 工具状态已刷新。",
        ["CliToolsDialogInstallDocker"] = "安装 Docker CLI",
        ["CliToolsDialogInstallDockerZip"] = "安装 Docker ZIP",
        ["CliToolsDialogInstallCompose"] = "安装 Compose",
        ["CliToolsDialogSelectComposeExe"] = "选择 Compose EXE",
        ["CliToolsDialogAddUserPath"] = "添加用户 PATH",
        ["CliToolsDialogAddSystemPath"] = "添加系统 PATH",
        ["CliToolsDialogNoFileSelected"] = "未选择文件。",
        ["DockerContextDefaultConfirmTitle"] = "使用 WSLC Desktop Docker context？",
        ["DockerContextDefaultConfirmContent"] = "这会在缺失时创建 docker context 'wslc-desktop'，然后将它设置为当前用户 Docker CLI 的默认 context。",
        ["DockerContextDefaultConfirmPrimary"] = "设为默认",
        ["DockerContextDefaultCreated"] = "Docker context “{0}” 已设为默认，并指向 {1}。",
        ["ShellStatusChecking"] = "检查中",
        ["ShellStatusDaemonOk"] = "Daemon 正常",
        ["ShellStatusDaemonOffline"] = "Daemon 离线",
        ["ShellStatusDaemonWarning"] = "Daemon 异常",
        ["ShellStatusRuntimeOk"] = "运行时正常",
        ["ShellStatusRuntimeIssue"] = "运行时异常",
        ["ShellStatusBackendUnknown"] = "后端未知",
        ["Start"] = "启动",
        ["Restart"] = "重启",
        ["Stop"] = "关闭",
        ["EngineReady"] = "就绪",
        ["EngineMissingComponents"] = "缺少组件",
        ["EngineUnsupported"] = "不支持",
        ["EngineError"] = "错误",
        ["EngineUnknown"] = "未知",
        ["ContainerCount"] = "{0} 个容器",
        ["ImageCount"] = "{0} 个缓存镜像",
        ["ImagesAvailable"] = "{0} 个镜像可用。",
        ["ImagesSummary"] = "{0} 个镜像",
        ["ImagePullStart"] = "正在开始拉取镜像...",
        ["ImagePulling"] = "正在拉取 {0}：{1}/{2} 字节",
        ["ImagePullingStatus"] = "正在拉取 {0}：{1}",
        ["ImagePullComplete"] = "镜像拉取完成。",
        ["ImagePullTaskQueued"] = "排队中",
        ["ImagePullTaskPulling"] = "拉取中",
        ["ImagePullTaskCompleted"] = "已完成",
        ["ImagePullTaskFailed"] = "失败",
        ["ImagePullTasksSummary"] = "{0} 个进行中 · 共 {1} 个",
        ["ImageDeleted"] = "镜像已删除。",
        ["PullImageTitle"] = "拉取镜像",
        ["PullImageReference"] = "镜像引用",
        ["Pull"] = "拉取",
        ["InUse"] = "使用中",
        ["Unused"] = "未使用",
        ["ComposeNoProjects"] = "尚未创建 Compose 项目。",
        ["ComposeProjectsLoaded"] = "已跟踪 {0} 个 Compose 项目。",
        ["ComposePlansGenerated"] = "已从 {2} 生成 {0} 个服务计划。",
        ["ComposeContainersCreated"] = "已创建并启动 {0} 个服务容器。",
        ["ComposeSummary"] = "{0} 个项目 · {1} 个计划服务",
        ["ComposeProjectStatus"] = "{0} 个运行中 / {1} 个服务",
        ["VolumesTracked"] = "默认 wslc 控制面中的 {0} 个数据卷。",
        ["VolumesSummary"] = "{0} 个数据卷",
        ["NamedVolumeCreated"] = "命名数据卷 {0} 已创建。",
        ["NamedVolumeDeleted"] = "命名数据卷 {0} 已删除。",
        ["CreateVolumeTitle"] = "新建数据卷",
        ["VolumeNameInput"] = "名称",
        ["VolumeSizeInput"] = "大小 MB",
        ["VolumeDetailName"] = "名称",
        ["VolumeDetailKind"] = "驱动",
        ["VolumeDetailSize"] = "大小",
        ["VolumeDetailUsedBy"] = "使用方",
        ["VolumeDetailCreated"] = "创建时间",
        ["NamedVolumeKind"] = "local",
        ["BindVolumeKind"] = "bind",
        ["NetworksPublishedPorts"] = "wslc 容器中的 {0} 个发布端点。",
        ["NetworkEndpointsSummary"] = "{0} 个发布端点",
        ["EndpointDetailContainer"] = "容器",
        ["EndpointDetailHostPort"] = "主机端口",
        ["EndpointDetailContainerPort"] = "容器端口",
        ["EndpointDetailProtocol"] = "协议",
        ["EndpointDetailUrl"] = "URL",
        ["ContainersLoaded"] = "{0} 个容器。",
        ["ContainersSummary"] = "{0} 个运行中 · {1} 个已停止",
        ["ContainersNoSelection"] = "未选择容器",
        ["ContainersSelectContainerDetail"] = "选择一个容器以查看详情。",
        ["InspectUnavailable"] = "检查数据不可用。",
        ["LogsUnavailable"] = "日志不可用。",
        ["PreviewTruncated"] = "... 还有 {0} 行。使用展开查看全部。",
        ["ContainerCreated"] = "容器 {0} 已创建。",
        ["ContainerStarted"] = "已请求启动 {0}。",
        ["ContainerStopped"] = "已请求停止 {0}。",
        ["ContainerRestarted"] = "已请求重启 {0}。",
        ["ContainerDeleted"] = "容器已删除。",
        ["TerminalNoContainer"] = "连接 Shell 前请选择一个正在运行的容器。",
        ["TerminalReadyMessage"] = "终端已就绪。连接正在运行的容器以打开 Shell。\n",
        ["TerminalConnectingMessage"] = "正在连接 {0}...\n",
        ["TerminalConnectedMessage"] = "[已连接：{0}]\n",
        ["TerminalConnectFailed"] = "[终端连接失败：{0}]\n",
        ["TerminalStateDisconnected"] = "未连接",
        ["TerminalStateConnecting"] = "正在连接",
        ["TerminalStateConnected"] = "已连接",
        ["TerminalStateExited"] = "已退出",
        ["TerminalStateFailed"] = "失败",
        ["ContainersLogsDialogTitle"] = "日志",
        ["ContainersTerminalDialogTitle"] = "终端",
        ["ContainersInspectDialogTitle"] = "检查",
        ["Delete"] = "删除",
        ["Cancel"] = "取消",
        ["Close"] = "关闭",
        ["Create"] = "创建",
        ["CreateContainerTitle"] = "新建容器",
        ["CreateContainerImage"] = "镜像",
        ["CreateContainerName"] = "名称（可选）",
        ["CreateContainerCommand"] = "命令",
        ["CreateContainerPorts"] = "端口（host:container，逗号分隔）",
        ["CreateContainerMounts"] = "挂载（source=>target，逗号分隔）",
        ["CreateContainerEnvironment"] = "环境变量（KEY=value，逗号分隔）",
        ["DeleteImageTitle"] = "删除镜像？",
        ["DeleteContainerTitle"] = "删除容器？",
        ["DeleteVolumeTitle"] = "删除命名数据卷",
        ["DeleteVolumeContent"] = "从默认 wslc 控制面删除命名数据卷“{0}”？"
    };

    public AppStringLocalizer(string? language = null)
    {
        CurrentLanguage = string.IsNullOrWhiteSpace(language) ? AppLanguage.English : language;
    }

    public string CurrentLanguage { get; }

    public string Get(string key)
    {
        return Get(key, CurrentLanguage);
    }

    public string Get(string key, string language)
    {
        var table = language == AppLanguage.Chinese ? Chinese : English;
        if (table.TryGetValue(key, out string? value))
        {
            return value;
        }

        return English.TryGetValue(key, out string? fallback) ? fallback : key;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(System.Globalization.CultureInfo.CurrentCulture, Get(key), args);
    }
}
